name: crediApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.15+20211201

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  device_info_plus: ^2.1.0
  dio: ^4.0.0
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  facebook_app_events: ^0.13.5
  file_picker: ^4.0.3
  firebase_analytics: ^8.1.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^2.0.11
  firebase_messaging: ^10.0.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.0
  flutter_flavor: ^3.0.3
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^6.0.0
  flutter_native_image: ^0.0.6+1
  flutter_native_timezone: ^2.0.0
  flutter_naver_login: ^1.2.2
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^0.14.0+3
  flutter_secure_storage: ^4.2.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_web_auth: ^0.3.1
  fluttertoast: ^8.0.7
  google_fonts: ^2.1.0
  heic_to_jpg: ^0.2.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  image_downloader: ^0.31.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  ionicons: ^0.1.2
  kakao_flutter_sdk: ^0.8.2
  logger: ^1.0.0
  logging: ^1.0.1

  navigation_history_observer: ^1.1.0
  notification_permissions: ^0.6.1
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  pattern_formatter: ^2.0.0
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.6
  photo_view: ^0.12.0
  random_string: ^2.2.0-nullsafety
  share_plus: ^2.1.4
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^3.1.0
  timeago: ^3.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.0.4
  uuid: ^3.0.4
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.0.14
  wechat_assets_picker: ^6.1.2
  wechat_camera_picker: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  test: ^1.16.8

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
# flutter pub run flutter_launcher_icons:main
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/texts/
    - assets/translations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
  # - family: SCore
  #   fonts:
  #     - asset: fonts/SCDream1.otf
  #       weight: 100
  #     - asset: fonts/SCDream2.otf
  #       weight: 200
  #     - asset: fonts/SCDream3.otf
  #       weight: 300
  #     - asset: fonts/SCDream4.otf
  #       weight: 400
  #     - asset: fonts/SCDream5.otf
  #       weight: 500
  #     - asset: fonts/SCDream6.otf
  #       weight: 600
  #     - asset: fonts/SCDream7.otf
  #       weight: 700
  #     - asset: fonts/SCDream8.otf
  #       weight: 800
  #     - asset: fonts/SCDream9.otf
  #       weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
